import { FolderHeart, LoaderCircle, Lock, Plus } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Avatar } from '../components/avatar';
import { Empty, ErrorBox, Loading, MacroCard } from '../components/cards';
import { createCollection, getCollection, listCollectionMacros, listCollections, listProfileMacros } from '../lib/catalog';
import { useAuth } from '../lib/auth';
import { isSupabaseConfigured, supabase } from '../lib/supabase';
import { useAsync } from '../lib/use-async';

export function CollectionsPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [formError, setFormError] = useState('');
  const { data, error, loading, reload } = useAsync(() => isSupabaseConfigured() ? listCollections(user?.id) : Promise.resolve([]), [user?.id]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; setBusy(true); setFormError(''); const form = new FormData(event.currentTarget); try { const id = await createCollection(user.id, String(form.get('name') ?? '').trim().slice(0, 100), String(form.get('description') ?? '').trim().slice(0, 1000), form.get('visibility') === 'private' ? 'private' : 'public'); setOpen(false); await reload(); navigate(`/collection/${id}`); } catch (caught) { setFormError(caught instanceof Error ? caught.message : 'Could not create the collection.'); } finally { setBusy(false); } }
  return <main className="mx-auto min-h-[75vh] max-w-7xl px-5 py-12 lg:px-8"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-300">Curated replay lists</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Collections</h1><p className="mt-3 text-sm text-zinc-500">Save related macros together in public or private lists.</p></div>{user ? <button onClick={() => setOpen((value) => !value)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-violet-500 px-4 text-xs font-semibold"><Plus className="h-4 w-4" />New collection</button> : <Link to="/login?return_to=%2Fcollections" className="rounded-xl bg-violet-500 px-4 py-3 text-xs font-semibold">Sign in to create</Link>}</header>
    {open && <form onSubmit={(event) => void create(event)} className="mt-7 grid gap-4 rounded-[24px] border border-white/[.075] bg-[#0e1118] p-5 sm:grid-cols-[1fr_1fr_auto]"><label><span className="mb-2 block text-[10px] text-zinc-500">Name</span><input required name="name" maxLength={100} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#11151d] px-3 text-sm outline-none" /></label><label><span className="mb-2 block text-[10px] text-zinc-500">Description</span><input name="description" maxLength={1000} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#11151d] px-3 text-sm outline-none" /></label><div className="flex items-end gap-2"><select name="visibility" className="h-11 rounded-xl border border-white/[.08] bg-[#11151d] px-3 text-xs"><option value="public">Public</option><option value="private">Private</option></select><button disabled={busy} className="grid h-11 w-11 place-items-center rounded-xl bg-violet-500">{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}</button></div>{formError && <p className="text-xs text-rose-200 sm:col-span-3">{formError}</p>}</form>}
    {error && <div className="mt-7"><ErrorBox message={error} /></div>}{loading ? <div className="mt-8"><Loading /></div> : data?.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map((collection) => <Link key={collection.id} to={`/collection/${collection.id}`} className="card-hover rounded-[22px] border border-white/[.075] bg-[#0e1118] p-5"><div className="flex items-center justify-between"><FolderHeart className="h-5 w-5 text-violet-300" />{collection.visibility === 'private' && <Lock className="h-3.5 w-3.5 text-zinc-600" />}</div><h2 className="mt-5 text-lg font-semibold">{collection.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-zinc-600">{collection.description ?? 'Macro collection'}</p><p className="mt-5 flex items-center gap-2 text-[10px] text-zinc-700"><Avatar profile={collection.owner} className="h-5 w-5 rounded-md text-[8px]" />{collection.collection_macros?.length ?? 0} macros · @{collection.owner?.username ?? 'player'}</p></Link>)}</div> : <div className="mt-8"><Empty title="No collections yet" text="Public collections will appear here after people create them." /></div>}
  </main>;
}

export function CollectionPage() {
  const { id = '' } = useParams();
  const { user } = useAuth();
  const [selected, setSelected] = useState('');
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState('');
  const { data, error, loading, reload } = useAsync(async () => { if (!isSupabaseConfigured()) return null; const collection = await getCollection(id); if (!collection) return null; const [macros, ownMacros] = await Promise.all([listCollectionMacros(id), user?.id === collection.owner_id ? listProfileMacros(user.id) : Promise.resolve([])]); return { collection, macros, ownMacros }; }, [id, user?.id]);
  async function add() { if (!user || !selected || !data) return; setBusy(true); setActionError(''); try { const { error: insertError } = await supabase().from('collection_macros').insert({ collection_id: id, macro_id: selected, added_by: user.id }); if (insertError) throw insertError; setSelected(''); await reload(); } catch (caught) { setActionError(caught instanceof Error ? caught.message : 'Could not add the macro.'); } finally { setBusy(false); } }
  if (loading) return <main className="mx-auto max-w-7xl px-5 py-12"><Loading /></main>;
  if (error) return <main className="mx-auto max-w-4xl px-5 py-12"><ErrorBox message={error} /></main>;
  if (!data) return <main className="mx-auto max-w-4xl px-5 py-12"><Empty title="Collection not found" text="It may be private, deleted, or unavailable." /></main>;
  const isOwner = user?.id === data.collection.owner_id;
  const available = data.ownMacros.filter((macro) => !data.macros.some((added) => added.id === macro.id));
  return <main className="mx-auto min-h-[75vh] max-w-7xl px-5 py-12 lg:px-8"><header className="rounded-[28px] border border-white/[.075] bg-[#0e1118] p-6 sm:p-8"><p className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-violet-300"><FolderHeart className="h-3.5 w-3.5" />{data.collection.visibility} collection</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em]">{data.collection.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-zinc-600"><Avatar profile={data.collection.owner} className="h-6 w-6 rounded-lg text-[9px]" />by @{data.collection.owner?.username ?? 'player'}</p>{data.collection.description && <p className="mt-5 max-w-3xl text-sm leading-6 text-zinc-400">{data.collection.description}</p>}</header>{isOwner && <section className="mt-5 flex flex-col gap-3 rounded-2xl border border-white/[.065] bg-[#0e1118] p-4 sm:flex-row"><select value={selected} onChange={(event) => setSelected(event.target.value)} className="h-11 min-w-0 flex-1 rounded-xl border border-white/[.08] bg-[#11151d] px-3 text-xs"><option value="">Choose one of your macros</option>{available.map((macro) => <option key={macro.id} value={macro.id}>{macro.title}</option>)}</select><button disabled={!selected || busy} onClick={() => void add()} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-500 px-4 text-xs font-semibold disabled:opacity-40">{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add macro</button></section>}{actionError && <p className="mt-3 text-xs text-rose-200">{actionError}</p>}<section className="mt-8">{data.macros.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.macros.map((macro) => <MacroCard key={macro.id} macro={macro} />)}</div> : <Empty title="Empty collection" text="No macros have been added to this collection yet." />}</section></main>;
}
