import type {
  FormatCompatibility,
  MacroFormatDefinition,
  ReplayToolDefinition,
} from './interfaces';
import {
  macroHubJsonExporter,
  macroHubJsonParser,
} from './formats/macrohub-json';
import { gdr2Exporter, gdr2Parser } from './formats/gdr2';
import { gdrJsonParser, gdrParser } from './formats/gdr1';
import { mhrBinaryParser, mhrJsonParser } from './formats/mhr';
import { cmlParser } from './formats/cml';
import { slcParser } from './formats/slc';
import { echoParser } from './formats/echo';
import { tasbotJsonParser } from './formats/tasbot';
import {
  amethystParser,
  fembotParser,
  kdbotParser,
  replayBotParser,
  rushParser,
  xbotParser,
  xdbotParser,
  zbotParser,
} from './formats/simple';
import { omegaBot2Parser, replayEngine3Parser, ybotParser } from './formats/versioned';
import { tcmParser } from './formats/tcm';
import { gdmoParser } from './formats/gdmo';

export const formatRegistry: readonly MacroFormatDefinition[] = [
  {
    id: 'macrohub-json',
    displayName: 'MacroHub Canonical JSON v1',
    shortName: 'MH JSON',
    extensions: ['.macrohub.json'],
    mediaTypes: ['application/vnd.macrohub.replay+json', 'application/json'],
    status: 'implemented',
    summary: 'Versioned, lossless canonical exchange format with strict validation.',
    parser: macroHubJsonParser,
    exporter: macroHubJsonExporter,
  },
  {
    id: 'gdr2',
    displayName: 'GDR2',
    shortName: 'GDR2',
    extensions: ['.gdr2'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Binary GDR2 parser and exporter based on the published version 2 format specification.',
    parser: gdr2Parser,
    exporter: gdr2Exporter,
  },
  {
    id: 'gdr',
    displayName: 'GDR',
    shortName: 'GDR',
    extensions: ['.gdr'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Verified GDR v1 MessagePack importer with extension-data preservation.',
    parser: gdrParser,
  },
  {
    id: 'gdr-json',
    displayName: 'GDR JSON',
    shortName: 'GDR JSON',
    extensions: ['.gdr.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'Verified GDR v1 JSON schema importer.',
    parser: gdrJsonParser,
  },
  {
    id: 'mhr',
    displayName: 'MHR',
    shortName: 'MHR',
    extensions: ['.mhr'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Version-aware MHR binary importer for verified HACK layouts.',
    parser: mhrBinaryParser,
  },
  {
    id: 'mhr-json',
    displayName: 'MHR JSON',
    shortName: 'MHR JSON',
    extensions: ['.mhr.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'Structure-checked MHR JSON importer.',
    parser: mhrJsonParser,
  },
  {
    id: 'cml',
    displayName: 'CML',
    shortName: 'CML',
    extensions: ['.cml'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'CML v1-v3 and v5-v6 importer with bounded gzip decoding.',
    parser: cmlParser,
  },
  {
    id: 'slc',
    displayName: 'SLC',
    shortName: 'SLC',
    extensions: ['.slc'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'SLC v1, v2, and v3 importer with content-based version detection.',
    parser: slcParser,
  },
  {
    id: 'xbot',
    displayName: 'XBOT',
    shortName: 'XBOT',
    extensions: ['.xbot'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'xBot frame-text replay importer.',
    parser: xbotParser,
  },
  {
    id: 'echo',
    displayName: 'ECHO',
    shortName: 'ECHO',
    extensions: ['.echo', '.echo.json'],
    mediaTypes: ['application/octet-stream', 'application/json'],
    status: 'implemented',
    summary: 'Echo META/METADBG binary and versioned JSON importer.',
    parser: echoParser,
  },
  {
    id: 'replaybot',
    displayName: 'RPLY v2',
    shortName: 'RPLY',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'ReplayBot v2 frame replay importer with RPLY header validation.',
    parser: replayBotParser,
  },
  {
    id: 'ybot',
    displayName: 'YBOT',
    shortName: 'YBOT',
    extensions: ['.ybot'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'yBot metadata, blob, and delta-action importer.',
    parser: ybotParser,
  },
  {
    id: 'omegabot-replay',
    displayName: 'REPLAY v2',
    shortName: 'REPLAY',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'OmegaBot v2 Bincode frame-replay importer with full-file schema validation.',
    parser: omegaBot2Parser,
  },
  {
    id: 'tasbot-json',
    displayName: 'TASBOT JSON',
    shortName: 'TASBOT JSON',
    extensions: ['.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'TASBot-specific JSON importer with structural detection.',
    parser: tasbotJsonParser,
  },
  {
    id: 'rush',
    displayName: 'RSH',
    shortName: 'RSH',
    extensions: ['.rsh', '.rush'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Rush fixed-record frame replay importer.',
    parser: rushParser,
  },
  {
    id: 'kdbot',
    displayName: 'KD',
    shortName: 'KD',
    extensions: ['.kd'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'KD fixed-record frame replay importer.',
    parser: kdbotParser,
  },
  {
    id: 'zbot',
    displayName: 'ZBF',
    shortName: 'ZBF',
    extensions: ['.zbf'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'zBot frame replay importer with delta and speedhack validation.',
    parser: zbotParser,
  },
  {
    id: 'fembot',
    displayName: 'FREPLAY',
    shortName: 'FREPLAY',
    extensions: ['.freplay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'FBRP-header Fembot replay importer.',
    parser: fembotParser,
  },
  {
    id: 'xdbot',
    displayName: 'XD',
    shortName: 'XD',
    extensions: ['.xd'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'xdBot pipe-delimited replay importer.',
    parser: xdbotParser,
  },
  {
    id: 'tcbot',
    displayName: 'TCM',
    shortName: 'TCM',
    extensions: ['.tcm'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'TCM v1/v2 importer with exact header and delta decoding.',
    parser: tcmParser,
  },
  {
    id: 'amethyst',
    displayName: 'THYST',
    shortName: 'THYST',
    extensions: ['.thyst'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Amethyst four-group timestamp replay importer.',
    parser: amethystParser,
  },
  {
    id: 'gdmo',
    displayName: 'MACRO',
    shortName: 'MACRO',
    extensions: ['.macro'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Modern and 2.2 GDMO replay importer with native-record validation.',
    parser: gdmoParser,
  },
  {
    id: 'replayengine3',
    displayName: 'RE3',
    shortName: 'RE3',
    extensions: ['.re3'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'ReplayEngine 3 Windows x64 native-layout importer.',
    parser: replayEngine3Parser,
  },

] as const;

export const replayToolRegistry: readonly ReplayToolDefinition[] = [
  { id: 'eclipse', displayName: 'Eclipse Menu', status: 'active', summary: 'Modern mod menu with replay playback using GDR2.' },
  { id: 'openhack', displayName: 'OpenHack', status: 'active', summary: 'Open-source mod menu with its own replay engine integration.' },
  { id: 'prism-menu', displayName: 'Prism Menu', status: 'active', summary: 'Mod menu tracked independently from its replay formats.' },
  { id: 'quartz', displayName: 'Quartz', status: 'active', summary: 'Replay tool with version-specific GDR compatibility.' },
  { id: 'silicate', displayName: 'Silicate', status: 'active', summary: 'Replay tool and converter associated with the SLC format family.' },
  { id: 'tcbot', displayName: 'TCBot', status: 'active', summary: 'Replay tool associated with versioned TCM files.' },
  { id: 'icreate-pro', displayName: 'iCreate Pro', status: 'active', summary: 'Geometry Dash mod menu with replay support on Apple platforms.' },
  { id: 'mega-hack', displayName: 'Mega Hack', status: 'active', summary: 'Popular mod framework with version-dependent replay support.' },
  { id: 'xbot', displayName: 'xdBot', status: 'active', summary: 'Replay tool with support varying by tool and format version.' },
  { id: 'echo', displayName: 'Echo', status: 'active', summary: 'Replay and macro tool tracked independently from file formats.' },
  { id: 'replaybot', displayName: 'ReplayBot', status: 'active', summary: 'Replay tool with explicit many-to-many compatibility records.' },
  { id: 'ybot', displayName: 'yBot', status: 'active', summary: 'Replay tool whose supported formats are versioned separately.' },
  { id: 'omegabot', displayName: 'OmegaBot', status: 'active', summary: 'Replay bot with multiple incompatible replay generations.' },
  { id: 'tasbot', displayName: 'TASBot', status: 'active', summary: 'Tool with a distinct JSON replay schema.' },
  { id: 'zbot', displayName: 'zBot', status: 'active', summary: 'Frame replay tool with its own ZBF format.' },
  { id: 'rush', displayName: 'Rush', status: 'active', summary: 'Replay tool tracked through explicit format relations.' },
  { id: 'kdbot', displayName: 'KD-Bot', status: 'active', summary: 'Replay tool with KD replay files.' },
  { id: 'fembot', displayName: 'Fembot', status: 'active', summary: 'Replay tool with FREPLAY files.' },
  { id: 'macrohub', displayName: 'MacroHub Converter', status: 'active', summary: 'Reference support for the canonical MacroHub exchange format.' },
] as const;

export const formatCompatibilityRegistry: readonly FormatCompatibility[] = [
  {
    formatId: 'macrohub-json',
    replayToolId: 'macrohub',
    direction: 'both',
    support: 'native',
    verification: 'verified',
    recommended: true,
    notes: 'Lossless reference interchange format.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'eclipse',
    direction: 'both',
    support: 'native',
    verification: 'community-reported',
    recommended: true,
    notes: 'Eclipse community macro repositories distribute GDR2 files; verify the installed Eclipse version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'mega-hack',
    direction: 'import',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Compatibility must be verified against the exact installed tool version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'xbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Catalog relation only; exporter is not implemented.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'xbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Catalog relation only; exporter is not implemented.',
  },
  {
    formatId: 'cml',
    replayToolId: 'xbot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Catalog relation is disabled for downloads until verified.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'echo',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'replaybot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'mhr',
    replayToolId: 'mega-hack',
    direction: 'both',
    support: 'native',
    verification: 'unknown',
    notes: 'A native relationship does not imply MacroHub can export this format.',
  },
  {
    formatId: 'ybot',
    replayToolId: 'ybot',
    direction: 'both',
    support: 'native',
    verification: 'unknown',
    notes: 'Exporter is intentionally unavailable.',
  },
  { formatId: 'replayengine3', replayToolId: 'openhack', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Version-specific relation.' },
  { formatId: 'gdr', replayToolId: 'prism-menu', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Verify against the installed Prism Menu version.' },
  { formatId: 'gdr', replayToolId: 'quartz', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Version-specific relation.' },
  { formatId: 'slc', replayToolId: 'silicate', direction: 'both', support: 'native', verification: 'community-reported', notes: 'SLC itself has multiple versions and extensions.' },
  { formatId: 'tcbot', replayToolId: 'tcbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'TCM version must match the tool.' },
  { formatId: 'gdr', replayToolId: 'icreate-pro', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Compatibility varies by product version.' },
  { formatId: 'omegabot-replay', replayToolId: 'omegabot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'OmegaBot major versions use distinct layouts.' },
  { formatId: 'tasbot-json', replayToolId: 'tasbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'JSON schema must be detected structurally.' },
  { formatId: 'zbot', replayToolId: 'zbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native ZBF relation.' },
  { formatId: 'rush', replayToolId: 'rush', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native Rush relation.' },
  { formatId: 'kdbot', replayToolId: 'kdbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native KD relation.' },
  { formatId: 'fembot', replayToolId: 'fembot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native FREPLAY relation.' },
] as const;

export type FormatId = (typeof formatRegistry)[number]['id'];
export type ReplayToolId = (typeof replayToolRegistry)[number]['id'];

export function getFormat(formatId: string): MacroFormatDefinition | undefined {
  return formatRegistry.find((format) => format.id === formatId);
}

export function getReplayTool(toolId: string): ReplayToolDefinition | undefined {
  return replayToolRegistry.find((tool) => tool.id === toolId);
}

export function getCompatibility(formatId: string, toolId: string): FormatCompatibility | undefined {
  return formatCompatibilityRegistry.find((item) => item.formatId === formatId && item.replayToolId === toolId);
}
