import type {
  FormatCompatibility,
  MacroFormatDefinition,
  ReplayToolDefinition,
} from './interfaces';
import {
  macroHubJsonExporter,
  macroHubJsonParser,
} from './formats/macrohub-json';
import { gdr2Exporter, gdr2Parser } from './formats/gdr2';

export const formatRegistry: readonly MacroFormatDefinition[] = [
  {
    id: 'macrohub-json',
    displayName: 'MacroHub Canonical JSON v1',
    shortName: 'MH JSON',
    extensions: ['.macrohub.json'],
    mediaTypes: ['application/vnd.macrohub.replay+json', 'application/json'],
    status: 'implemented',
    summary: 'Versioned, lossless canonical exchange format with strict validation.',
    parser: macroHubJsonParser,
    exporter: macroHubJsonExporter,
  },
  {
    id: 'gdr2',
    displayName: 'GDR2',
    shortName: 'GDR2',
    extensions: ['.gdr2'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Binary GDR2 parser and exporter based on the published version 2 format specification.',
    parser: gdr2Parser,
    exporter: gdr2Exporter,
  },
  {
    id: 'gdr',
    displayName: 'GDR',
    shortName: 'GDR',
    extensions: ['.gdr'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder. No files are generated until the specification is verified.',
  },
  {
    id: 'gdr-json',
    displayName: 'GDR JSON',
    shortName: 'GDR JSON',
    extensions: ['.gdr.json'],
    mediaTypes: ['application/json'],
    status: 'planned',
    summary: 'Recognized catalog entry; generic JSON is never assumed to match this format.',
  },
  {
    id: 'json',
    displayName: 'Generic JSON',
    shortName: 'JSON',
    extensions: ['.json'],
    mediaTypes: ['application/json'],
    status: 'planned',
    summary: 'Intentionally unsupported because JSON alone is not a replay specification.',
  },
  {
    id: 'mhr',
    displayName: 'Mega Hack Replay',
    shortName: 'MHR',
    extensions: ['.mhr'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder for version-specific Mega Hack replay formats.',
  },
  {
    id: 'mhr-json',
    displayName: 'Mega Hack Replay JSON',
    shortName: 'MHR JSON',
    extensions: ['.mhr.json'],
    mediaTypes: ['application/json'],
    status: 'planned',
    summary: 'Registry placeholder awaiting authoritative fixtures.',
  },
  {
    id: 'cml',
    displayName: 'CML',
    shortName: 'CML',
    extensions: ['.cml'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder; no fake exporter is included.',
  },
  {
    id: 'slc',
    displayName: 'SLC',
    shortName: 'SLC',
    extensions: ['.slc'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder; converter availability is fail-closed.',
  },
  {
    id: 'xbot',
    displayName: 'xdBot Replay',
    shortName: 'xdBot',
    extensions: ['.xbot'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Tool-named catalog placeholder; formats and replay tools remain separate records.',
  },
  {
    id: 'echo',
    displayName: 'Echo Replay',
    shortName: 'Echo',
    extensions: ['.echo'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder awaiting versioned format evidence.',
  },
  {
    id: 'replaybot',
    displayName: 'ReplayBot Replay',
    shortName: 'ReplayBot',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder awaiting verified golden files.',
  },
  {
    id: 'ybot',
    displayName: 'yBot Replay',
    shortName: 'yBot',
    extensions: ['.ybot'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry placeholder; not offered as a generated download.',
  },
  {
    id: 'omegabot-replay',
    displayName: 'OmegaBot Replay',
    shortName: 'OmegaBot',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Versioned OmegaBot replay family; detector adapters are separated by major version.',
  },
  {
    id: 'tasbot-json',
    displayName: 'TASBot Replay JSON',
    shortName: 'TASBot',
    extensions: ['.json'],
    mediaTypes: ['application/json'],
    status: 'planned',
    summary: 'TASBot-specific JSON; generic JSON is never treated as this format automatically.',
  },
  {
    id: 'rush',
    displayName: 'Rush Replay',
    shortName: 'Rush',
    extensions: ['.rush'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for Rush replay files.',
  },
  {
    id: 'kdbot',
    displayName: 'KD-Bot Replay',
    shortName: 'KD-Bot',
    extensions: ['.kd'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for KD-Bot replay files.',
  },
  {
    id: 'zbot',
    displayName: 'zBot Frame Replay',
    shortName: 'zBot',
    extensions: ['.zbf'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for zBot frame replay files.',
  },
  {
    id: 'fembot',
    displayName: 'Fembot Replay',
    shortName: 'Fembot',
    extensions: ['.freplay'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for Fembot replay files.',
  },
  {
    id: 'xdbot',
    displayName: 'XDBot Replay',
    shortName: 'XDBot',
    extensions: ['.xd'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for XDBot 2.2 replay files.',
  },
  {
    id: 'tcbot',
    displayName: 'TCBot Replay',
    shortName: 'TCM',
    extensions: ['.tcm'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for TCBot TCM files.',
  },
  {
    id: 'amethyst',
    displayName: 'Amethyst Replay',
    shortName: 'Amethyst',
    extensions: ['.thyst'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Registry entry for Amethyst replay files.',
  },
  {
    id: 'gdmo',
    displayName: 'GDMO Replay',
    shortName: 'GDMO',
    extensions: ['.macro'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'Versioned GDMegaOverlay replay family.',
  },
  {
    id: 'replayengine3',
    displayName: 'ReplayEngine 3',
    shortName: 'RE3',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'planned',
    summary: 'ReplayEngine 3 registry entry with content-based detection required.',
  },

] as const;

export const replayToolRegistry: readonly ReplayToolDefinition[] = [
  { id: 'eclipse', displayName: 'Eclipse Menu', status: 'active', summary: 'Modern mod menu with replay playback using GDR2.' },
  { id: 'openhack', displayName: 'OpenHack', status: 'active', summary: 'Open-source mod menu with its own replay engine integration.' },
  { id: 'prism-menu', displayName: 'Prism Menu', status: 'active', summary: 'Mod menu tracked independently from its replay formats.' },
  { id: 'quartz', displayName: 'Quartz', status: 'active', summary: 'Replay tool with version-specific GDR compatibility.' },
  { id: 'silicate', displayName: 'Silicate', status: 'active', summary: 'Replay tool and converter associated with the SLC format family.' },
  { id: 'tcbot', displayName: 'TCBot', status: 'active', summary: 'Replay tool associated with versioned TCM files.' },
  { id: 'icreate-pro', displayName: 'iCreate Pro', status: 'active', summary: 'Geometry Dash mod menu with replay support on Apple platforms.' },
  { id: 'mega-hack', displayName: 'Mega Hack', status: 'active', summary: 'Popular mod framework with version-dependent replay support.' },
  { id: 'xbot', displayName: 'xdBot', status: 'active', summary: 'Replay tool with support varying by tool and format version.' },
  { id: 'echo', displayName: 'Echo', status: 'active', summary: 'Replay and macro tool tracked independently from file formats.' },
  { id: 'replaybot', displayName: 'ReplayBot', status: 'active', summary: 'Replay tool with explicit many-to-many compatibility records.' },
  { id: 'ybot', displayName: 'yBot', status: 'active', summary: 'Replay tool whose supported formats are versioned separately.' },
  { id: 'omegabot', displayName: 'OmegaBot', status: 'active', summary: 'Replay bot with multiple incompatible replay generations.' },
  { id: 'tasbot', displayName: 'TASBot', status: 'active', summary: 'Tool with a distinct JSON replay schema.' },
  { id: 'zbot', displayName: 'zBot', status: 'active', summary: 'Frame replay tool with its own ZBF format.' },
  { id: 'rush', displayName: 'Rush', status: 'active', summary: 'Replay tool tracked through explicit format relations.' },
  { id: 'kdbot', displayName: 'KD-Bot', status: 'active', summary: 'Replay tool with KD replay files.' },
  { id: 'fembot', displayName: 'Fembot', status: 'active', summary: 'Replay tool with FREPLAY files.' },
  { id: 'macrohub', displayName: 'MacroHub Converter', status: 'active', summary: 'Reference support for the canonical MacroHub exchange format.' },
] as const;

export const formatCompatibilityRegistry: readonly FormatCompatibility[] = [
  {
    formatId: 'macrohub-json',
    replayToolId: 'macrohub',
    direction: 'both',
    support: 'native',
    verification: 'verified',
    recommended: true,
    notes: 'Lossless reference interchange format.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'eclipse',
    direction: 'both',
    support: 'native',
    verification: 'community-reported',
    recommended: true,
    notes: 'Eclipse community macro repositories distribute GDR2 files; verify the installed Eclipse version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'mega-hack',
    direction: 'import',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Compatibility must be verified against the exact installed tool version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'xbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Catalog relation only; exporter is not implemented.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'xbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Catalog relation only; exporter is not implemented.',
  },
  {
    formatId: 'json',
    replayToolId: 'xbot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Generic JSON is ambiguous; a versioned specification is required.',
  },
  {
    formatId: 'cml',
    replayToolId: 'xbot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Catalog relation is disabled for downloads until verified.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'echo',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'replaybot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'mhr',
    replayToolId: 'mega-hack',
    direction: 'both',
    support: 'native',
    verification: 'unknown',
    notes: 'A native relationship does not imply MacroHub can export this format.',
  },
  {
    formatId: 'ybot',
    replayToolId: 'ybot',
    direction: 'both',
    support: 'native',
    verification: 'unknown',
    notes: 'Exporter is intentionally unavailable.',
  },
  { formatId: 'replayengine3', replayToolId: 'openhack', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Version-specific relation.' },
  { formatId: 'gdr', replayToolId: 'prism-menu', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Verify against the installed Prism Menu version.' },
  { formatId: 'gdr', replayToolId: 'quartz', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Version-specific relation.' },
  { formatId: 'slc', replayToolId: 'silicate', direction: 'both', support: 'native', verification: 'community-reported', notes: 'SLC itself has multiple versions and extensions.' },
  { formatId: 'tcbot', replayToolId: 'tcbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'TCM version must match the tool.' },
  { formatId: 'gdr', replayToolId: 'icreate-pro', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Compatibility varies by product version.' },
  { formatId: 'omegabot-replay', replayToolId: 'omegabot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'OmegaBot major versions use distinct layouts.' },
  { formatId: 'tasbot-json', replayToolId: 'tasbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'JSON schema must be detected structurally.' },
  { formatId: 'zbot', replayToolId: 'zbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native ZBF relation.' },
  { formatId: 'rush', replayToolId: 'rush', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native Rush relation.' },
  { formatId: 'kdbot', replayToolId: 'kdbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native KD relation.' },
  { formatId: 'fembot', replayToolId: 'fembot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native FREPLAY relation.' },
] as const;

export type FormatId = (typeof formatRegistry)[number]['id'];
export type ReplayToolId = (typeof replayToolRegistry)[number]['id'];

export function getFormat(formatId: string): MacroFormatDefinition | undefined {
  return formatRegistry.find((format) => format.id === formatId);
}

export function getReplayTool(toolId: string): ReplayToolDefinition | undefined {
  return replayToolRegistry.find((tool) => tool.id === toolId);
}

export function getCompatibility(formatId: string, toolId: string): FormatCompatibility | undefined {
  return formatCompatibilityRegistry.find((item) => item.formatId === formatId && item.replayToolId === toolId);
}
