import type {
  FormatCompatibility,
  MacroFormatDefinition,
  ReplayToolDefinition,
} from './interfaces';
import {
  macroHubJsonExporter,
  macroHubJsonParser,
} from './formats/macrohub-json';
import { gdr2Exporter, gdr2Parser } from './formats/gdr2';
import { gdrJsonParser, gdrParser } from './formats/gdr1';
import { mhrBinaryParser, mhrJsonParser } from './formats/mhr';
import { cmlParser } from './formats/cml';
import { slcParser } from './formats/slc';
import { echoParser } from './formats/echo';
import { tasbotJsonParser } from './formats/tasbot';
import {
  amethystParser,
  fembotParser,
  kdbotParser,
  replayBotParser,
  rushParser,
  xbotParser,
  xdbotParser,
  zbotParser,
} from './formats/simple';
import { omegaBot2Parser, ybotParser } from './formats/versioned';
import { replayEngine4Exporter, replayEngine4Parser } from './formats/replay-engine4';
import { tcmParser } from './formats/tcm';
import { gdmoParser } from './formats/gdmo';
import {
  amethystExporter,
  cmlExporter,
  echoExporter,
  fembotExporter,
  gdmoExporter,
  gdrExporter,
  gdrJsonExporter,
  kdbotExporter,
  mhrBinaryExporter,
  mhrJsonExporter,
  omegaBot2Exporter,
  replayBotExporter,
  rushExporter,
  slcExporter,
  tasbotJsonExporter,
  tcmExporter,
  xbotExporter,
  xdbotExporter,
  ybotExporter,
  zbotExporter,
} from './formats/verified-exporters';

export const formatRegistry: readonly MacroFormatDefinition[] = [
  {
    id: 'macrohub-json',
    displayName: 'MacroHub Replay v2',
    shortName: 'MacroHub',
    extensions: ['.macrohub'],
    mediaTypes: ['application/vnd.macrohub.replay'],
    status: 'implemented',
    summary: 'Delta-packed MessagePack and gzip container preserving the complete canonical replay losslessly.',
    parser: macroHubJsonParser,
    exporter: macroHubJsonExporter,
  },
  {
    id: 'gdr2',
    displayName: 'GDR2',
    shortName: 'GDR2',
    extensions: ['.gdr2'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Binary GDR2 parser and exporter based on the published version 2 format specification.',
    parser: gdr2Parser,
    exporter: gdr2Exporter,
  },
  {
    id: 'gdr',
    displayName: 'GDR',
    shortName: 'GDR',
    extensions: ['.gdr'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'GDR v1 MessagePack import and version-pinned export.',
    parser: gdrParser,
    exporter: gdrExporter,
  },
  {
    id: 'gdr-json',
    displayName: 'GDR JSON',
    shortName: 'GDR JSON',
    extensions: ['.gdr.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'GDR v1 JSON import and version-pinned export.',
    parser: gdrJsonParser,
    exporter: gdrJsonExporter,
  },
  {
    id: 'mhr',
    displayName: 'MHR',
    shortName: 'MHR',
    extensions: ['.mhr'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Version-aware MHR import with a strict v7 HACK exporter.',
    parser: mhrBinaryParser,
    exporter: mhrBinaryExporter,
  },
  {
    id: 'mhr-json',
    displayName: 'MHR JSON',
    shortName: 'MHR JSON',
    extensions: ['.mhr.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'Structure-checked MHR JSON import and export.',
    parser: mhrJsonParser,
    exporter: mhrJsonExporter,
  },
  {
    id: 'cml',
    displayName: 'CML',
    shortName: 'CML',
    extensions: ['.cml'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'CML v1-v3 and v5-v6 import with a strict CML v1 exporter.',
    parser: cmlParser,
    exporter: cmlExporter,
  },
  {
    id: 'slc',
    displayName: 'SLC',
    shortName: 'SLC',
    extensions: ['.slc'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'SLC v1, v2, and v3 import with a strict SLC v1 exporter.',
    parser: slcParser,
    exporter: slcExporter,
  },
  {
    id: 'xbot',
    displayName: 'XBOT',
    shortName: 'XBOT',
    extensions: ['.xbot'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'xBot frame-text replay import and export.',
    parser: xbotParser,
    exporter: xbotExporter,
  },
  {
    id: 'echo',
    displayName: 'ECHO',
    shortName: 'ECHO',
    extensions: ['.echo', '.echo.json'],
    mediaTypes: ['application/octet-stream', 'application/json'],
    status: 'implemented',
    summary: 'Echo META/METADBG and JSON import with META binary export.',
    parser: echoParser,
    exporter: echoExporter,
  },
  {
    id: 'replaybot',
    displayName: 'RPLY v2',
    shortName: 'RPLY',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'ReplayBot v2 frame replay import and export with RPLY validation.',
    parser: replayBotParser,
    exporter: replayBotExporter,
  },
  {
    id: 'ybot',
    displayName: 'YBOT',
    shortName: 'YBOT',
    extensions: ['.ybot'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'yBot metadata, blob, and delta-action import and export.',
    parser: ybotParser,
    exporter: ybotExporter,
  },
  {
    id: 'omegabot-replay',
    displayName: 'REPLAY v2',
    shortName: 'REPLAY',
    extensions: ['.replay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'OmegaBot v2 Bincode frame-replay import and export.',
    parser: omegaBot2Parser,
    exporter: omegaBot2Exporter,
  },
  {
    id: 'tasbot-json',
    displayName: 'TASBOT JSON',
    shortName: 'TASBOT JSON',
    extensions: ['.json'],
    mediaTypes: ['application/json'],
    status: 'implemented',
    summary: 'TASBot-specific JSON import and export with structural detection.',
    parser: tasbotJsonParser,
    exporter: tasbotJsonExporter,
  },
  {
    id: 'rush',
    displayName: 'RSH',
    shortName: 'RSH',
    extensions: ['.rsh', '.rush'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Rush fixed-record frame replay import and export.',
    parser: rushParser,
    exporter: rushExporter,
  },
  {
    id: 'kdbot',
    displayName: 'KD',
    shortName: 'KD',
    extensions: ['.kd'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'KD fixed-record frame replay import and export.',
    parser: kdbotParser,
    exporter: kdbotExporter,
  },
  {
    id: 'zbot',
    displayName: 'ZBF',
    shortName: 'ZBF',
    extensions: ['.zbf'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'zBot frame replay import and export with exact rate-pair validation.',
    parser: zbotParser,
    exporter: zbotExporter,
  },
  {
    id: 'fembot',
    displayName: 'FREPLAY',
    shortName: 'FREPLAY',
    extensions: ['.freplay'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'FBRP-header Fembot replay import and export.',
    parser: fembotParser,
    exporter: fembotExporter,
  },
  {
    id: 'xdbot',
    displayName: 'XD',
    shortName: 'XD',
    extensions: ['.xd'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'xdBot pipe-delimited replay import and export.',
    parser: xdbotParser,
    exporter: xdbotExporter,
  },
  {
    id: 'tcbot',
    displayName: 'TCM',
    shortName: 'TCM',
    extensions: ['.tcm'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'TCM v1/v2 import with a strict TCM v1 exporter.',
    parser: tcmParser,
    exporter: tcmExporter,
  },
  {
    id: 'amethyst',
    displayName: 'THYST',
    shortName: 'THYST',
    extensions: ['.thyst'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Amethyst four-group timestamp replay import and export.',
    parser: amethystParser,
    exporter: amethystExporter,
  },
  {
    id: 'gdmo',
    displayName: 'MACRO',
    shortName: 'MACRO',
    extensions: ['.macro'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Modern and 2.2 GDMO import with safe 2.2 action export.',
    parser: gdmoParser,
    exporter: gdmoExporter,
  },
  {
    id: 'replayengine4',
    displayName: 'RE4',
    shortName: 'RE4',
    extensions: ['.re4'],
    mediaTypes: ['application/octet-stream'],
    status: 'implemented',
    summary: 'Current GDH Replay Engine v4 binary replay.',
    parser: replayEngine4Parser,
    exporter: replayEngine4Exporter,
  },

] as const;

export const replayToolRegistry: readonly ReplayToolDefinition[] = [
  { id: 'eclipse', displayName: 'Eclipse Menu', status: 'active', summary: 'Modern mod menu with replay playback using GDR2.' },
  { id: 'openhack', displayName: 'OpenHack', status: 'active', summary: 'Open-source mod menu with its own replay engine integration.' },
  { id: 'gdh', displayName: 'GDH', status: 'active', summary: 'Geometry Dash mod menu with Replay Engine v4.' },
  { id: 'prism-menu', displayName: 'Prism Menu', status: 'active', summary: 'Mod menu tracked independently from its replay formats.' },
  { id: 'quartz', displayName: 'Quartz', status: 'active', summary: 'Replay tool with version-specific GDR compatibility.' },
  { id: 'silicate', displayName: 'Silicate', status: 'active', summary: 'Replay tool and converter associated with the SLC format family.' },
  { id: 'tcbot', displayName: 'TCBot', status: 'active', summary: 'Replay tool associated with versioned TCM files.' },
  { id: 'icreate-pro', displayName: 'iCreate Pro', status: 'active', summary: 'Geometry Dash mod menu with replay support on Apple platforms.' },
  { id: 'mega-hack', displayName: 'Mega Hack', status: 'active', summary: 'Popular mod framework with version-dependent replay support.' },
  { id: 'xbot', displayName: 'xBot', status: 'active', summary: 'Replay tool with its own frame-text XBOT format.' },
  { id: 'xdbot', displayName: 'xdBot', status: 'active', summary: 'Replay tool with XD and version-dependent GDR family support.' },
  { id: 'echo', displayName: 'Echo', status: 'active', summary: 'Replay and macro tool tracked independently from file formats.' },
  { id: 'replaybot', displayName: 'ReplayBot', status: 'active', summary: 'Replay tool with explicit many-to-many compatibility records.' },
  { id: 'ybot', displayName: 'yBot', status: 'active', summary: 'Replay tool whose supported formats are versioned separately.' },
  { id: 'omegabot', displayName: 'OmegaBot', status: 'active', summary: 'Replay bot with multiple incompatible replay generations.' },
  { id: 'tasbot', displayName: 'TASBot', status: 'active', summary: 'Tool with a distinct JSON replay schema.' },
  { id: 'zbot', displayName: 'zBot', status: 'active', summary: 'Frame replay tool with its own ZBF format.' },
  { id: 'rush', displayName: 'Rush', status: 'active', summary: 'Replay tool tracked through explicit format relations.' },
  { id: 'kdbot', displayName: 'KD-Bot', status: 'active', summary: 'Replay tool with KD replay files.' },
  { id: 'fembot', displayName: 'Fembot', status: 'active', summary: 'Replay tool with FREPLAY files.' },
  { id: 'amethyst', displayName: 'Amethyst', status: 'active', summary: 'Replay tool with THYST timestamp files.' },
  { id: 'gdmo', displayName: 'GDMO', status: 'active', summary: 'Replay tool with versioned MACRO files.' },
  { id: 'macrohub', displayName: 'MacroHub Converter', status: 'active', summary: 'Reference support for the canonical MacroHub exchange format.' },
] as const;

export const formatCompatibilityRegistry: readonly FormatCompatibility[] = [
  {
    formatId: 'macrohub-json',
    replayToolId: 'macrohub',
    direction: 'both',
    support: 'native',
    verification: 'verified',
    recommended: true,
    notes: 'Lossless reference interchange format.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'eclipse',
    direction: 'both',
    support: 'native',
    verification: 'community-reported',
    recommended: true,
    notes: 'Eclipse community macro repositories distribute GDR2 files; verify the installed Eclipse version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'mega-hack',
    direction: 'import',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Compatibility must be verified against the exact installed tool version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'xdbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Generated GDR2 support can vary by installed xdBot version.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'xdbot',
    direction: 'both',
    support: 'partial',
    verification: 'community-reported',
    notes: 'Generated GDR support can vary by installed xdBot version.',
  },
  {
    formatId: 'cml',
    replayToolId: 'xdbot',
    direction: 'import',
    support: 'partial',
    verification: 'community-reported',
    notes: 'CML support is version-specific; verify against the installed xdBot version.',
  },
  {
    formatId: 'gdr2',
    replayToolId: 'echo',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'gdr',
    replayToolId: 'replaybot',
    direction: 'import',
    support: 'partial',
    verification: 'unknown',
    notes: 'Version-specific evidence required.',
  },
  {
    formatId: 'mhr',
    replayToolId: 'mega-hack',
    direction: 'both',
    support: 'native',
    verification: 'community-reported',
    notes: 'MacroHub generates the strict MHR v7 HACK layout.',
  },
  {
    formatId: 'ybot',
    replayToolId: 'ybot',
    direction: 'both',
    support: 'native',
    verification: 'community-reported',
    notes: 'MacroHub generates the versioned yBot action layout.',
  },
  { formatId: 'replayengine4', replayToolId: 'gdh', direction: 'both', support: 'native', verification: 'verified', recommended: true, notes: 'Official GDH Replay Engine v4 format.' },
  { formatId: 'gdr', replayToolId: 'prism-menu', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Verify against the installed Prism Menu version.' },
  { formatId: 'gdr', replayToolId: 'quartz', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Version-specific relation.' },
  { formatId: 'slc', replayToolId: 'silicate', direction: 'both', support: 'native', verification: 'community-reported', notes: 'SLC itself has multiple versions and extensions.' },
  { formatId: 'tcbot', replayToolId: 'tcbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'TCM version must match the tool.' },
  { formatId: 'gdr', replayToolId: 'icreate-pro', direction: 'import', support: 'partial', verification: 'community-reported', notes: 'Compatibility varies by product version.' },
  { formatId: 'omegabot-replay', replayToolId: 'omegabot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'OmegaBot major versions use distinct layouts.' },
  { formatId: 'tasbot-json', replayToolId: 'tasbot', direction: 'both', support: 'native', verification: 'verified', notes: 'Native TASBOT JSON schema.' },
  { formatId: 'zbot', replayToolId: 'zbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native ZBF relation.' },
  { formatId: 'rush', replayToolId: 'rush', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native Rush relation.' },
  { formatId: 'kdbot', replayToolId: 'kdbot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native KD relation.' },
  { formatId: 'fembot', replayToolId: 'fembot', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Native FREPLAY relation.' },
  { formatId: 'xbot', replayToolId: 'xbot', direction: 'both', support: 'native', verification: 'verified', notes: 'Native XBOT frame-text format.' },
  { formatId: 'xdbot', replayToolId: 'xdbot', direction: 'both', support: 'native', verification: 'verified', notes: 'Native XD pipe-delimited format.' },
  { formatId: 'echo', replayToolId: 'echo', direction: 'both', support: 'native', verification: 'verified', notes: 'Native Echo META format.' },
  { formatId: 'replaybot', replayToolId: 'replaybot', direction: 'both', support: 'native', verification: 'verified', notes: 'Native ReplayBot v2 RPLY format.' },
  { formatId: 'mhr-json', replayToolId: 'mega-hack', direction: 'both', support: 'native', verification: 'community-reported', notes: 'Mega Hack Replay JSON format.' },
  { formatId: 'amethyst', replayToolId: 'amethyst', direction: 'both', support: 'native', verification: 'verified', notes: 'Native THYST timestamp format.' },
  { formatId: 'gdmo', replayToolId: 'gdmo', direction: 'both', support: 'native', verification: 'verified', notes: 'Native GDMO MACRO format.' },
  { formatId: 'gdr', replayToolId: 'macrohub', direction: 'both', support: 'native', verification: 'verified', notes: 'MacroHub can parse and generate strict GDR v1 files.' },
  { formatId: 'gdr-json', replayToolId: 'macrohub', direction: 'both', support: 'native', verification: 'verified', notes: 'MacroHub can parse and generate GDR JSON files.' },
] as const;

export type FormatId = (typeof formatRegistry)[number]['id'];
export type ReplayToolId = (typeof replayToolRegistry)[number]['id'];

export function getFormat(formatId: string): MacroFormatDefinition | undefined {
  return formatRegistry.find((format) => format.id === formatId);
}

export function getReplayTool(toolId: string): ReplayToolDefinition | undefined {
  return replayToolRegistry.find((tool) => tool.id === toolId);
}

export function getCompatibility(formatId: string, toolId: string): FormatCompatibility | undefined {
  return formatCompatibilityRegistry.find((item) => item.formatId === formatId && item.replayToolId === toolId);
}
